# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-toml
    -   id: check-json
    -   id: check-yaml
    -   id: trailing-whitespace
